dataset:
  _target_: "src.dataset.datalayers.AudioDataset"
  manifest_filepath: ${validation_datasets}
  max_duration: ${val_max_duration}
  min_duration: ${val_min_duration}
  n_segments: ${val_n_segments}
  sample_rate: ${sample_rate}
  trim: false
dataloader_params:
  drop_last: false
  shuffle: false
  batch_size: 4
  num_workers: 1
