dataset:
  _target_: "src.dataset.datalayers.AudioDataset"
  manifest_filepath: ${train_dataset}
  max_duration: ${train_max_duration}
  min_duration: ${train_min_duration}
  n_segments: ${train_n_segments}
  sample_rate: ${sample_rate}
  trim: false
dataloader_params:
  drop_last: false
  shuffle: true
  batch_size: 16
  num_workers: 4
