name: ???
sample_rate: 22050
labels: [' ', '!', '"', "'", '(', ')', ',', '-', '.', ':', ';', '?', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h',
        'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
n_fft: 1024
n_mels: 80
fmax: null
n_stride: 256
pad_value: -11.52
gate_target_weight: 5.
train_dataset: ???
validation_datasets: ???

log_val_sample_idx: null

model:
  labels: ${labels}
  log_val_sample_idx: ${log_val_sample_idx}
  gate_target_weight: ${gate_target_weight}

  train_ds:
    dataset:
      _target_: "nemo.collections.asr.data.audio_to_text.AudioToCharDataset"
      parser: "en"
      manifest_filepath: ${train_dataset}
      max_duration: 11
      min_duration: 0.1
      trim: false
      int_values: false
      normalize: true
      sample_rate: ${sample_rate}
    dataloader_params:
      drop_last: false
      shuffle: true
      batch_size: 16
      num_workers: 4

  validation_ds:
    dataset:
      _target_: "nemo.collections.asr.data.audio_to_text.AudioToCharDataset"
      parser: "en"
      manifest_filepath: ${validation_datasets}
      max_duration: 11
      min_duration: 0.1
      int_values: false
      normalize: true
      sample_rate: ${sample_rate}
      trim: false
    dataloader_params:
      drop_last: false
      shuffle: false
      batch_size: 16
      num_workers: 4

  preprocessor:
    _target_: nemo.collections.asr.parts.preprocessing.features.FilterbankFeatures
    dither: 0.0
    nfilt: ${n_mels}
    frame_splicing: 1
    highfreq: ${fmax}
    log: true
    log_zero_guard_type: clamp
    log_zero_guard_value: 1e-05
    lowfreq: 0
    mag_power: 1.0
    n_fft: ${n_fft}
    n_window_size: 1024
    n_window_stride: ${n_stride}
    normalize: null
    pad_to: 16
    pad_value: ${pad_value}
    preemph: null
    sample_rate: ${sample_rate}
    window: hann

  encoder:
    _target_: src.modules.transformer_tts.Encoder
    encoder_n_convolutions: 3
    encoder_embedding_dim: 512
    encoder_kernel_size: 5
    encoder_dropout_p: 0.5
    pos_dropout_p: 0.1
    num_layers: 3
    hidden_size: 512
    inner_size: 2048
    head_size: 64
    num_attention_heads: 8
    attn_score_dropout: 0.05
    attn_layer_dropout: 0.1
    ffn_dropout: 0.1
    pre_ln: True
    pre_ln_final_layer_norm: False

  decoder:
    _target_: src.modules.transformer_tts.Decoder
    n_mel_channels: ${n_mels}
    prenet_dropout_p: 0.5
    pos_dropout_p: 0.1
    num_layers: 3
    hidden_size: 512
    inner_size: 2048
    head_size: 64
    num_attention_heads: 8
    attn_score_dropout: 0.05
    attn_layer_dropout: 0.1
    ffn_dropout: 0.1
    pre_ln: True
    pre_ln_final_layer_norm: False
    gate_threshold: 0.5
    early_stopping: true
    max_decoder_steps: 1000

  postnet:
    _target_: src.modules.transformer_tts.Postnet
    n_mel_channels: ${n_mels}
    p_dropout: 0.5
    postnet_embedding_dim: 512
    postnet_kernel_size: 5
    postnet_n_convolutions: 5

  optim:
    name: adam
    lr: 1

    sched:
      name: NoamAnnealing
      warmup_steps: 10000
      min_lr: 1e-5
      d_model: ${model.encoder.hidden_size}

trainer:
  gpus: 1 # number of gpus
  max_epochs: ???
  num_nodes: 1
  accelerator: ddp
  accumulate_grad_batches: 1
  checkpoint_callback: False  # Provided by exp_manager
  logger: False  # Provided by exp_manager
  gradient_clip_val: 1.0
  flush_logs_every_n_steps: 1000
  log_every_n_steps: 50
  check_val_every_n_epoch: 1

exp_manager:
  exp_dir: null
  name: ${name}
  create_tensorboard_logger: True
  create_checkpoint_callback: True
