name: ???
train_dataset: ???
validation_datasets: ???

sample_rate: 22050
n_mels: 80
n_fft: 1024
fmax: 8000
n_stride: 256
pad_value: -11.52

train_n_segments: 8192
train_max_duration: null
train_min_duration: 0.75

val_n_segments: -1
val_max_duration: null
val_min_duration: null

defaults:
  - model/generator: v1
  - model/train_ds: train_ds
  - model/validation_ds: val_ds

model:
  preprocessor:
    _target_: nemo.collections.asr.parts.preprocessing.features.FilterbankFeatures
    dither: 0.0
    frame_splicing: 1
    nfilt: ${n_mels}
    highfreq: ${fmax}
    log: true
    log_zero_guard_type: clamp
    log_zero_guard_value: 1e-05
    lowfreq: 0
    mag_power: 1.0
    n_fft: ${n_fft}
    n_window_size: ${n_fft}
    n_window_stride: ${n_stride}
    normalize: null
    pad_to: 0
    pad_value: ${pad_value}
    preemph: null
    sample_rate: ${sample_rate}
    window: hann
    use_grads: false
    exact_pad: true

  optim:
    _target_: torch.optim.AdamW
    lr: 0.0002
    betas: [0.8, 0.99]

  sched:
    name: CosineAnnealing
    min_lr: 1e-5
    warmup_ratio: 0.02

  max_steps: 2500000
  l1_loss_factor: 45
  denoise_strength: 0.0025

trainer:
  gpus: -1 # number of gpus
  max_steps: ${model.max_steps}
  num_nodes: 1
  accelerator: ddp
  accumulate_grad_batches: 1
  checkpoint_callback: False  # Provided by exp_manager
  logger: False  # Provided by exp_manager
  flush_logs_every_n_steps: 1000
  log_every_n_steps: 50
  check_val_every_n_epoch: 1

exp_manager:
  exp_dir: null
  name: ${name}
  create_tensorboard_logger: True
  create_checkpoint_callback: True
  checkpoint_callback_params:
    monitor: "val_loss"
    mode: "min"
